[package]
name = "tsp-template"
version = "0.1.0"
license = "PolyForm-Noncommercial-1.0.0"
description = "TSP-template desktop game"
edition = "2021"
rust-version = "1.98.1"

[lib]
name = "tsp_template_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
